FROM nginx:latest

# Nginx 설정 파일 복사
COPY ./default.conf /etc/nginx/conf.d/default.conf

# SSL 인증서 및 개인 키 복사
COPY ./fullchain.pem /etc/nginx/pem/
COPY ./privkey.pem /etc/nginx/pem/

# 기타 정적 파일이 있다면 복사
# COPY /home/ubuntu/basilfarm-frontend/.next /usr/share/nginx/html/

# 컨테이너가 80번 포트를 사용할 수 있도록 열기 (HTTP 사용하는 경우)
EXPOSE 80

# 컨테이너가 443번 포트를 사용할 수 있도록 열기 (HTTPS 사용하는 경우)
EXPOSE 443

# Nginx 실행
CMD ["nginx", "-g", "daemon off;"]
